In [6]:
import pandas as pd

dir = '/home/dsutterlin/projects/genPain/'
df = pd.read_csv(dir + 'results/' + 'SCEBLmri_Finaldata_TxT_N36.csv')
print(df.shape)
df.head

(3456, 12)

<bound method NDFrame.head of       blocktrial  block  temp  condition   RTexp  RTpain        exp  \
0            1.0      1  48.0        1.0  2459.0  2459.0  29.039301
1            2.0      1  49.0        2.0  2078.0  1373.0  10.078143
2            3.0      1  50.0        8.0  3133.0  3039.0  32.486785
3            4.0      1  49.0        7.0  3550.0  3765.0  30.475753
4            5.0      1  49.0        5.0  1571.0  2876.0   6.056079
...          ...    ...   ...        ...     ...     ...        ...
3451        12.0      6  49.0        4.0  1202.0   908.0  71.270972
3452        13.0      6  49.0        5.0   675.0   693.0  14.100207
3453        14.0      6  49.0        5.0   793.0   969.0  14.962078
3454        15.0      6  50.0        6.0   588.0   693.0  12.089175
3455        16.0      6  48.0        1.0   657.0   448.0  29.326592

           pain       mfpe  cues  social  conflict
0     10.652724 -18.386578    -1      -1        -1
1     12.663755   2.585613    -1      -1        -1
2     20.420593 -12.066192     1       1        -1
3     18.984142 -11.491611     1       1        -1
4     23.006205  16.950126     1      -1         1
...         ...        ...   ...     ...       ...
3451  22.718915 -48.552057    -1       1         1
3452  10.365433  -3.734774     1      -1         1
3453  34.785107  19.823029     1      -1         1
3454  25.591818  13.502643     1      -1         1
3455  30.763043   1.436451    -1      -1        -1

[3456 rows x 12 columns]>

In [9]:
print(df.isna().sum())
df.describe()

blocktrial      3
block           0
temp            3
condition       3
RTexp           4
RTpain          4
exp           101
pain           93
mfpe          181
cues            0
social          0
conflict        0
dtype: int64

,blocktrial,block,temp,condition,RTexp,RTpain,exp,pain,mfpe,cues,social,conflict
count,3453.000000,3456.000000,3453.000000,3453.000000,3452.000000,3452.000000,3355.000000,3363.000000,3275.000000,3456.000000,3456.000000,3456.000000
mean,8.494353,3.500000,48.999421,4.498407,2209.274623,2336.960023,37.033356,31.475817,-5.297419,-0.000579,0.000579,-0.001157
std,4.608394,1.708072,0.707107,2.291682,836.324997,860.752523,22.593220,22.020145,17.374870,1.000145,1.000145,1.000144
min,1.000000,1.000000,48.000000,1.000000,0.000000,0.000000,0.000000,0.000000,-85.899793,-1.000000,-1.000000,-1.000000
25%,4.000000,2.000000,48.000000,2.000000,1672.000000,1791.000000,18.696851,12.663755,-13.502643,-1.000000,-1.000000,-1.000000
50%,8.000000,3.500000,49.000000,4.000000,2183.000000,2322.000000,33.061365,28.752011,-3.160193,-1.000000,1.000000,-1.000000
75%,12.000000,5.000000,49.000000,6.000000,2748.000000,2900.000000,56.331878,48.575040,4.022064,1.000000,1.000000,1.000000
max,16.000000,6.000000,50.000000,8.000000,4499.000000,4492.000000,100.000000,94.828775,66.387037,1.000000,1.000000,1.000000